### ISSUE TITLE
pawn capturing move is interpreted as a move by bishop

### ISSUE THREAD

**Issue by werenskjold** [iigorr/pgn.net#12]
On move 19 in this game http://pastebin.com/raw.php?i=pJWh7psi, the move by the pawn is interpreted as a move by bishop. Any idea of how ti fix this?

**Comment by iigorr** [comment]
Hi warenskjold,

thank you for reporing. Actually this was supposed to be fixed long ago (https://github.com/iigorr/pgn.net/issues/11#issuecomment-110921408).The fix should have been in version 1.1.1.0 but somehow I failed to package the NuGet package correctly. Sorry for that.

I have uploaded version 1.1.1.1 with the correctly packaged DLLs. Hope everything works now. If not, please let me know.

Cheers,

Igor
